/* =============================================
   1. AUTH TABLE (MUST BE FIRST)
   ============================================= */
CREATE TABLE app_user (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_apoge VARCHAR2(20) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_app_role
        CHECK (role IN ('ADMIN','STUDENT','TEACHER'))
);

/* =============================================
   2. ENTITIES
   ============================================= */
CREATE TABLE student (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_apoge VARCHAR2(20) UNIQUE NOT NULL,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    academic_level VARCHAR2(20) NOT NULL,
    enrollment_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT chk_student_level
        CHECK (academic_level IN ('LICENCE','DEUG','MASTER','DOCTORAT')),
    CONSTRAINT fk_student_auth
        FOREIGN KEY (code_apoge) REFERENCES app_user(code_apoge)
);

CREATE TABLE departement (
    departement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(40) UNIQUE NOT NULL
);

CREATE TABLE instructor (
    instructor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_apoge VARCHAR2(20) UNIQUE NOT NULL,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    departement_id NUMBER NOT NULL,
    CONSTRAINT fk_instructor_auth
        FOREIGN KEY (code_apoge) REFERENCES app_user(code_apoge),
    CONSTRAINT fk_instructor_dept
        FOREIGN KEY (departement_id) REFERENCES departement(departement_id)
);

CREATE TABLE salle (
    salle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_salle VARCHAR2(20) UNIQUE NOT NULL,
    capacity NUMBER NOT NULL CHECK (capacity > 0),
    building VARCHAR2(50) NOT NULL
);

CREATE TABLE course (
    course_code NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) UNIQUE NOT NULL,
    credits NUMBER NOT NULL CHECK (credits > 0)
);

CREATE TABLE semester (
    semester_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    CHECK (start_date < end_date)
);

CREATE TABLE prerequisite (
    course_code NUMBER NOT NULL,
    prereq_code NUMBER NOT NULL,
    min_grade CHAR(1) NOT NULL,
    PRIMARY KEY (course_code, prereq_code),
    CONSTRAINT chk_prereq_grade
        CHECK (min_grade IN ('A','B','C','D','E','F')),
    FOREIGN KEY (course_code) REFERENCES course(course_code),
    FOREIGN KEY (prereq_code) REFERENCES course(course_code)
);

CREATE TABLE section (
    section_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code NUMBER NOT NULL,
    semester_id NUMBER NOT NULL,
    instructor_id NUMBER NOT NULL,
    salle_id NUMBER NOT NULL,
    max_capacity NUMBER NOT NULL,
    current_enrolled NUMBER DEFAULT 0 NOT NULL,
    day_of_week VARCHAR2(20) NOT NULL,
    start_time DATE NOT NULL,
    end_time DATE NOT NULL,
    FOREIGN KEY (course_code) REFERENCES course(course_code),
    FOREIGN KEY (semester_id) REFERENCES semester(semester_id),
    FOREIGN KEY (instructor_id) REFERENCES instructor(instructor_id),
    FOREIGN KEY (salle_id) REFERENCES salle(salle_id)
);

CREATE TABLE registration (
    registration_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    section_id NUMBER NOT NULL,
    registration_date DATE DEFAULT SYSDATE NOT NULL,
    status VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_registration_status
        CHECK (status IN ('ACTIVE','DROPPED','CANCELLED')),
    CONSTRAINT uq_student_section
        UNIQUE (student_id, section_id),
    FOREIGN KEY (student_id) REFERENCES student(student_id),
    FOREIGN KEY (section_id) REFERENCES section(section_id)
);

CREATE TABLE course_result (
    result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    course_code NUMBER NOT NULL,
    grade CHAR(1) NOT NULL,
    status VARCHAR2(10) NOT NULL,
    CONSTRAINT chk_course_grade
        CHECK (grade IN ('A','B','C','D','E','F')),
    CONSTRAINT chk_course_status
        CHECK (status IN ('PASS','NV')),
    FOREIGN KEY (student_id) REFERENCES student(student_id),
    FOREIGN KEY (course_code) REFERENCES course(course_code)
);
CREATE TABLE grades_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER,
    course_code NUMBER,
    old_grade CHAR(1),
    new_grade CHAR(1),
    change_date DATE DEFAULT SYSDATE,
    user_action VARCHAR2(10) -- 'UPDATE'
);
/* =============================================
   1. user login
   ============================================= */
CREATE OR REPLACE VIEW v_users_login AS
SELECT code_apoge, role FROM app_user;
/* =============================================
   2. section capacity
   ============================================= */
CREATE OR REPLACE VIEW v_section_capacity AS
SELECT
    s.section_id,
    c.title,
    sa.code_salle,
    s.max_capacity,
    s.current_enrolled,
    (s.max_capacity - s.current_enrolled) AS available_seats
FROM section s
JOIN course c ON s.course_code = c.course_code
JOIN salle sa ON s.salle_id = sa.salle_id;

CREATE INDEX idx_student_code_apoge ON student(code_apoge);
CREATE INDEX idx_instructor_code_apoge ON instructor(code_apoge);
CREATE INDEX idx_registration_student ON registration(student_id);
CREATE INDEX idx_section_course ON section(course_code);
/* =============================================
   VIEW 3: REGISTRATION DETAILS
   ============================================= */
CREATE OR REPLACE VIEW v_registration_details AS
SELECT 
    r.registration_id,
    r.student_id,
    st.first_name,
    st.last_name,
    c.title AS course_title,
    r.status,
    r.registration_date
FROM 
    registration r
    JOIN student st ON r.student_id = st.student_id
    JOIN section se ON r.section_id = se.section_id
    JOIN course c ON se.course_code = c.course_code;

/* =============================================
   VIEW 4: SECTION DETAILS
   ============================================= */
CREATE OR REPLACE VIEW v_section_details AS
SELECT 
    se.section_id,
    c.title AS course_title,
    s.name AS semester_name,
    i.name AS instructor_name,
    sa.code_salle AS salle_code,
    se.day_of_week,
    se.start_time,
    se.end_time,
    se.max_capacity,
    se.current_enrolled
FROM 
    section se
    JOIN course c ON se.course_code = c.course_code
    JOIN semester s ON se.semester_id = s.semester_id
    JOIN instructor i ON se.instructor_id = i.instructor_id
    JOIN salle sa ON se.salle_id = sa.salle_id;
/* =============================================
   VIEW 5: releve de note
   ============================================= */
CREATE OR REPLACE VIEW v_student_transcript AS
SELECT 
    s.code_apoge,
    s.first_name || ' ' || s.last_name AS full_name,
    c.title AS course_title,
    c.credits,
    cr.grade,
    CASE cr.grade
        WHEN 'A' THEN 4
        WHEN 'B' THEN 3
        WHEN 'C' THEN 2
        WHEN 'D' THEN 1
        ELSE 0
    END AS gpa_points,
    cr.status
FROM student s
JOIN course_result cr ON s.student_id = cr.student_id
JOIN course c ON cr.course_code = c.course_code;
/* =============================================
   VIEW 6: RESULTATS GROUPES PAR SEMESTRE
   ============================================= */
CREATE OR REPLACE VIEW v_student_results_grouped AS
SELECT 
    s.code_apoge,
    s.first_name,
    s.last_name,
    sem.name AS semester_name,
    sem.start_date, -- N7tajuh bach n-triyw (Sort) mn l-9dim l jdid
    c.title AS course_title,
    c.credits,
    cr.grade,
    cr.status
FROM 
    student s
    JOIN course_result cr ON s.student_id = cr.student_id
    JOIN course c ON cr.course_code = c.course_code
    -- Hna kan-linkiw m3a Registration bach n3rfu had l-cours f ay semestre daz
    JOIN registration r ON s.student_id = r.student_id
    JOIN section sec ON r.section_id = sec.section_id AND sec.course_code = c.course_code
    JOIN semester sem ON sec.semester_id = sem.semester_id
ORDER BY 
    s.code_apoge,
    sem.start_date ASC, -- Semesters lwala huma l-3adyin
    c.title;
/* =============================================
   VIEW 7: DETAILS COMPLETS POUR ETUDIANT
   (Cours + Prof + Dept + Salle)
   ============================================= */
CREATE OR REPLACE VIEW v_student_enrollment_extended AS
SELECT 
    s.code_apoge,
    r.registration_id,
    r.status AS registration_status,
    sec.section_id,
    c.title AS course_title,
    i.name AS instructor_name,
    i.email AS instructor_email,
    d.name AS departement_name,
    sa.code_salle,
    sa.building AS salle_building,
    sec.day_of_week,
    sec.start_time,
    sec.end_time
FROM registration r
JOIN student s ON r.student_id = s.student_id
JOIN section sec ON r.section_id = sec.section_id
JOIN course c ON sec.course_code = c.course_code
JOIN instructor i ON sec.instructor_id = i.instructor_id
JOIN departement d ON i.departement_id = d.departement_id
JOIN salle sa ON sec.salle_id = sa.salle_id;
/* =============================================
   4. TRIGGERS
   ============================================= */
CREATE OR REPLACE TRIGGER trg_section_capacity
BEFORE INSERT OR UPDATE ON section
FOR EACH ROW
DECLARE
    v_capacity NUMBER;
BEGIN
    SELECT capacity INTO v_capacity FROM salle WHERE salle_id = :NEW.salle_id;
    IF :NEW.max_capacity > v_capacity THEN
        RAISE_APPLICATION_ERROR(-20010,'Section capacity exceeds room capacity');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_check_registration_capacity
BEFORE INSERT ON registration
FOR EACH ROW
DECLARE
    v_current NUMBER;
    v_max NUMBER;
BEGIN
    SELECT current_enrolled, max_capacity INTO v_current, v_max
    FROM section WHERE section_id = :NEW.section_id;
    IF v_current >= v_max THEN
        RAISE_APPLICATION_ERROR(-20020,'No available seats');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_inc_enrolled
AFTER INSERT ON registration
FOR EACH ROW
BEGIN
    UPDATE section SET current_enrolled = current_enrolled + 1 WHERE section_id = :NEW.section_id;
END;
/

CREATE OR REPLACE TRIGGER trg_dec_enrolled
AFTER DELETE ON registration
FOR EACH ROW
BEGIN
    UPDATE section SET current_enrolled = current_enrolled - 1 WHERE section_id = :OLD.section_id;
END;
/

CREATE OR REPLACE TRIGGER trg_check_section_time
BEFORE INSERT OR UPDATE ON section
FOR EACH ROW
BEGIN
    IF :NEW.start_time >= :NEW.end_time THEN
        RAISE_APPLICATION_ERROR(-20030,'Invalid section time range');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_check_prerequisites
BEFORE INSERT ON registration
FOR EACH ROW
DECLARE
    v_course_code NUMBER;
    v_missing_prereqs NUMBER;
BEGIN
    SELECT course_code INTO v_course_code 
    FROM section 
    WHERE section_id = :NEW.section_id;
    SELECT COUNT(*) INTO v_missing_prereqs
    FROM prerequisite p
    WHERE p.course_code = v_course_code
    AND NOT EXISTS (
        SELECT 1 
        FROM course_result cr
        WHERE cr.student_id = :NEW.student_id
          AND cr.course_code = p.prereq_code
          AND cr.grade <= p.min_grade  
          AND cr.status = 'PASS'       
    );

    IF v_missing_prereqs > 0 THEN
        RAISE_APPLICATION_ERROR(-20040, 'Prerequisites not met: Student does not meet grade requirements for this course.');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_audit_grades
AFTER UPDATE OF grade ON course_result
FOR EACH ROW
BEGIN
    IF :OLD.grade != :NEW.grade THEN
        INSERT INTO grades_audit (student_id, course_code, old_grade, new_grade, user_action)
        VALUES (:OLD.student_id, :OLD.course_code, :OLD.grade, :NEW.grade, 'UPDATE');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_auto_status
BEFORE INSERT OR UPDATE ON course_result
FOR EACH ROW
BEGIN
    IF :NEW.grade IN ('A', 'B', 'C', 'D') THEN
        :NEW.status := 'PASS';
    ELSIF :NEW.grade IN ('E', 'F') THEN
        :NEW.status := 'NV'; -- Non Validé
    END IF;
END;
/